"""add subscription plans and vendor subscriptions

Revision ID: 5eb681501ebe
Revises: 3192f945049d
Create Date: 2026-08-25 21:33:52.073139

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eb681501ebe'
down_revision: Union[str, None] = '3192f945049d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_DEFAULT_PLAN_ID = uuid.uuid4()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_gnf', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        sa.table(
            'subscription_plans',
            sa.column('id', sa.UUID()),
            sa.column('name', sa.String()),
            sa.column('price_gnf', sa.Integer()),
            sa.column('duration_days', sa.Integer()),
            sa.column('is_active', sa.Boolean()),
        ),
        [
            {
                'id': _DEFAULT_PLAN_ID,
                'name': 'Premium mensuel',
                'price_gnf': 20000,
                'duration_days': 30,
                'is_active': True,
            }
        ],
    )
    op.create_table('vendor_subscriptions',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'expired', 'cancelled', name='subscription_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_subscriptions')
    op.drop_table('subscription_plans')
    op.execute("DROP TYPE subscription_status")
    # ### end Alembic commands ###
